// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iniznkbcurzfevcafaeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluaXpua2JjdXJ6ZmV2Y2FmYWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODI0OTYsImV4cCI6MjA3Mzg1ODQ5Nn0.cNV5p_C1WULsyHwTR6xTV4mdGcOLeg-QGMAzmajZatc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});